dist: trusty
sudo: required
language: generic
env:
  global:
  - SUITE=xenial
  - ARCH=amd64
  - PROJECT=ubuntu-server
  - SUBPROJECT=live
  - MIRROR=http://archive.ubuntu.com/ubuntu/
  - BINARYFORMAT=iso-hybrid
  - LB_SYSLINUX_THEME=ubuntu-xenial
  - IMAGE_TARGETS=iso
  - LIVE_CONFIG_DEBUG=true
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y ubuntu-defaults-builder
- sudo apt-get install -y livecd-rootfs
- wget http://archive.ubuntu.com/ubuntu/pool/main/l/livecd-rootfs/livecd-rootfs_2.441_amd64.deb
- wget http://archive.ubuntu.com/ubuntu/pool/main/l/live-build/live-build_3.0~a57-1ubuntu29_all.deb
# Install latest livecd-rootfs
- sudo dpkg -i livecd-rootfs_2.441_amd64.deb live-build_3.0~a57-1ubuntu29_all.deb
# dependency for syslinux-themes-ubuntu-xenial
- wget http://archive.ubuntu.com/ubuntu/pool/main/s/syslinux/isolinux_6.03+dfsg-14.1_all.deb
- wget http://archive.ubuntu.com/ubuntu/pool/main/s/syslinux-themes-ubuntu/syslinux-themes-ubuntu-xenial_12_amd64.deb
- sudo dpkg -i syslinux-themes-ubuntu-xenial_12_amd64.deb isolinux_6.03+dfsg-14.1_all.deb
# upgrade syslinux-common in host, used in lb_binary_syslinux
- wget http://archive.ubuntu.com/ubuntu/pool/main/s/syslinux/syslinux-common_6.03+dfsg-14.1_all.deb
- sudo dpkg -i syslinux-common_6.03+dfsg-14.1_all.deb
install:
- echo "Nothing to install"
script:
- cp -a /usr/share/livecd-rootfs/live-build/auto .
- lb config --initramfs-compression=gzip
- sudo lb build --verbose
after_script:
- ls -al
deploy:
  provider: releases
  api_key:
    secure: ZOaF5Toz5aNqF2y2DbbVaF3RloZJnECNA6cWxgzNmI4KblyzKmBIr7m4HjqTqQZFYohsyLV7hm7s0QGbVuSlaI+03PoMuPYNK+oqtximL7qUu6D/eng1AZT3mizh91o80fRMrVc7Pv/pgFXlinMPCNDbuWpnEq45xG0S9CspFpynJp8Y9A/w7LkI6SuLkoWXR4qP03NTRG8HM8KXbrEQyTWdYZAU5UfkaMqWhe3mutw3CmydJ414CwNVa/AiIQds+8rrGxc3MRn89Xe2iVotrEuLiO5LeXHNuXEaprfldugEMdit7/MkzGNSzsJ7Xxq2p1zToHCiwi7RCwOsCwnufbJGYTDPsTXwKU063hkXeH1DZOXLQGKaYSXwWQxKaIzEmbWIfnZsvtw6WEXJV3YH1znqpuZ37xSHz24PxEUdyCVv0UK1SfburCcWQ2YMr5YE5COpG63JWYFDGY2rYX0EtU2da7J0VlGiju2Z0vl1LfPARWUw5pi0E1gJbg1+u0BA0i4OUr6eY0f3cEFtOdVVVHoF3l5TKdRzyFtCUEUMsPKYHp4P4nHUN0jnhLtlhzM3g4XZK/zAdLTlP70pNjU8evpr4houc2YDTaP46Mrojz5YKoJq4U0VPPp9C35pbNrwp5YvvvwjEyJwStvisXzUZUGgbFRa3HgrbVD0WF31LHs=
  file:
    - binary.contents
    - binary.hybrid.iso
    - binary.log
    - binary.packages
    - livecd.ubuntu-server.iso
    - livecd.ubuntu-server.manifest
    - livecd.ubuntu-server.manifest-remove
    - livecd.ubuntu-server.rootfs.tar.gz
  on:
    repo: swem/livecd.xenial
